# -*- coding: utf-8 -*-
"""entrenamiento_neurona.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W-HvAPCTv5xU0G3qeQNrYdMfmV16DqZd
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

# carga del dataset balanceado
df = pd.read_csv("/content/dataset_balanceado_con_smote.csv")

features = ["age", "ejection_fraction", "serum_creatinine", "serum_sodium"]
target = "DEATH_EVENT"

X = df[features].values
y = df[target].values

# normalización de los datos
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# entrenemineto con una neurona
neurona = LogisticRegression()
neurona.fit(X_scaled, y)

# valores del peso y sesgo del modelo entrenado
pesos = neurona.coef_[0]
bias = neurona.intercept_[0]

# parámetros para estandarizar los datos
media = scaler.mean_
des_estandar = scaler.scale_

print("Pesos de la neurona:" ,pesos)
print("\nBias:" ,bias)
print("\nMedia:" ,media)
print("\nDesviación estándar:" ,des_estandar)

