# -*- coding: utf-8 -*-
"""pesos_entrenamiento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14dZ19r-RKQHhAqg0w5D6eOkjb2JxRpjp
"""

import numpy as np

# pesos y parámetros aprendidos en el entrenamiento
pesos = np.array([0.58667069, -0.77868936, 0.75603927, -0.26559091])
bias = 0.034625444844061735
media = np.array([61.8615337, 36.65270936, 1.49424358, 36.15517241])
des_estandar = np.array([12.02083453, 12.12253042, 1.08296504, 4.51904131])